// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first, then .env as fallback
// This ensures Prisma CLI always sees environment variables when run from terminal
config({ path: ".env.local" });
config(); // Load .env as fallback

// Get database URL for migrations (DIRECT_URL for Supabase Session pooler, fallback to DATABASE_URL)
const databaseUrl = process.env.DIRECT_URL ?? process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error(
    "DATABASE_URL or DIRECT_URL must be set in environment variables. " +
    "Check .env.local file."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
