/**
 * Demo products for each game
 * Used when database is empty
 */

export interface DemoProduct {
  id: string;
  sku: string;
  title: string;
  description: string | null;
  priceRub: number;
  category: string | null;
  provider: 'MANUAL';
  isActive: boolean;
  imageUrl: string | null;
  gameSlug: string;
}

export const DEMO_PRODUCTS: DemoProduct[] = [
  // Mobile Legends: Bang Bang
  {
    id: 'demo-ml-1',
    sku: 'ML-DIAMONDS-50',
    title: '50 Diamonds',
    description: 'Игровая валюта Mobile Legends',
    priceRub: 99,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'mobile-legends',
  },
  {
    id: 'demo-ml-2',
    sku: 'ML-DIAMONDS-170',
    title: '170 Diamonds',
    description: 'Игровая валюта Mobile Legends',
    priceRub: 299,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'mobile-legends',
  },
  {
    id: 'demo-ml-3',
    sku: 'ML-DIAMONDS-310',
    title: '310 Diamonds',
    description: 'Игровая валюта Mobile Legends',
    priceRub: 499,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'mobile-legends',
  },
  {
    id: 'demo-ml-4',
    sku: 'ML-TOPUP-100',
    title: 'Пополнение счета 100₽',
    description: 'Пополнение игрового счета',
    priceRub: 100,
    category: 'Top-up',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'mobile-legends',
  },
  {
    id: 'demo-ml-5',
    sku: 'ML-PASS-MONTHLY',
    title: 'Месячный пропуск',
    description: 'Премиум пропуск на месяц',
    priceRub: 349,
    category: 'Pass',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'mobile-legends',
  },
  // Free Fire
  {
    id: 'demo-ff-1',
    sku: 'FF-DIAMONDS-100',
    title: '100 Diamonds',
    description: 'Игровая валюта Free Fire',
    priceRub: 199,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'free-fire',
  },
  {
    id: 'demo-ff-2',
    sku: 'FF-DIAMONDS-310',
    title: '310 Diamonds',
    description: 'Игровая валюта Free Fire',
    priceRub: 499,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'free-fire',
  },
  {
    id: 'demo-ff-3',
    sku: 'FF-DIAMONDS-520',
    title: '520 Diamonds',
    description: 'Игровая валюта Free Fire',
    priceRub: 799,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'free-fire',
  },
  {
    id: 'demo-ff-4',
    sku: 'FF-TOPUP-500',
    title: 'Пополнение счета 500₽',
    description: 'Пополнение игрового счета',
    priceRub: 500,
    category: 'Top-up',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'free-fire',
  },
  {
    id: 'demo-ff-5',
    sku: 'FF-PASS-ROYAL',
    title: 'Royal Pass',
    description: 'Королевский пропуск',
    priceRub: 599,
    category: 'Pass',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'free-fire',
  },
  // Roblox
  {
    id: 'demo-roblox-1',
    sku: 'ROBLOX-ROBUX-80',
    title: '80 Robux',
    description: 'Игровая валюта Roblox',
    priceRub: 99,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'roblox',
  },
  {
    id: 'demo-roblox-2',
    sku: 'ROBLOX-ROBUX-400',
    title: '400 Robux',
    description: 'Игровая валюта Roblox',
    priceRub: 399,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'roblox',
  },
  {
    id: 'demo-roblox-3',
    sku: 'ROBLOX-ROBUX-800',
    title: '800 Robux',
    description: 'Игровая валюта Roblox',
    priceRub: 799,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'roblox',
  },
  {
    id: 'demo-roblox-4',
    sku: 'ROBLOX-PREMIUM',
    title: 'Roblox Premium',
    description: 'Премиум подписка на месяц',
    priceRub: 299,
    category: 'Pass',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'roblox',
  },
  {
    id: 'demo-roblox-5',
    sku: 'ROBLOX-TOPUP-1000',
    title: 'Пополнение счета 1000₽',
    description: 'Пополнение игрового счета',
    priceRub: 1000,
    category: 'Top-up',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'roblox',
  },
  // Genshin Impact
  {
    id: 'demo-gi-1',
    sku: 'GI-CRYSTALS-60',
    title: '60 Crystals',
    description: 'Игровая валюта Genshin Impact',
    priceRub: 99,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'genshin-impact',
  },
  {
    id: 'demo-gi-2',
    sku: 'GI-CRYSTALS-330',
    title: '330 Crystals',
    description: 'Игровая валюта Genshin Impact',
    priceRub: 499,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'genshin-impact',
  },
  {
    id: 'demo-gi-3',
    sku: 'GI-CRYSTALS-1090',
    title: '1090 Crystals',
    description: 'Игровая валюта Genshin Impact',
    priceRub: 1499,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'genshin-impact',
  },
  {
    id: 'demo-gi-4',
    sku: 'GI-BATTLE-PASS',
    title: 'Battle Pass',
    description: 'Боевой пропуск',
    priceRub: 699,
    category: 'Pass',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'genshin-impact',
  },
  {
    id: 'demo-gi-5',
    sku: 'GI-TOPUP-2000',
    title: 'Пополнение счета 2000₽',
    description: 'Пополнение игрового счета',
    priceRub: 2000,
    category: 'Top-up',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'genshin-impact',
  },
  // Honkai: Star Rail
  {
    id: 'demo-hsr-1',
    sku: 'HSR-CRYSTALS-60',
    title: '60 Crystals',
    description: 'Игровая валюта Honkai: Star Rail',
    priceRub: 99,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'honkai-star-rail',
  },
  {
    id: 'demo-hsr-2',
    sku: 'HSR-CRYSTALS-330',
    title: '330 Crystals',
    description: 'Игровая валюта Honkai: Star Rail',
    priceRub: 499,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'honkai-star-rail',
  },
  {
    id: 'demo-hsr-3',
    sku: 'HSR-CRYSTALS-1090',
    title: '1090 Crystals',
    description: 'Игровая валюта Honkai: Star Rail',
    priceRub: 1499,
    category: 'Currency',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'honkai-star-rail',
  },
  {
    id: 'demo-hsr-4',
    sku: 'HSR-BATTLE-PASS',
    title: 'Battle Pass',
    description: 'Боевой пропуск',
    priceRub: 699,
    category: 'Pass',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'honkai-star-rail',
  },
  {
    id: 'demo-hsr-5',
    sku: 'HSR-TOPUP-1500',
    title: 'Пополнение счета 1500₽',
    description: 'Пополнение игрового счета',
    priceRub: 1500,
    category: 'Top-up',
    provider: 'MANUAL',
    isActive: true,
    imageUrl: null,
    gameSlug: 'honkai-star-rail',
  },
];

export function getDemoProductsByGame(gameSlug: string): DemoProduct[] {
  return DEMO_PRODUCTS.filter((product) => product.gameSlug === gameSlug);
}

